Fix rotation issues
hrynko/vue-pdf-embed pull request #136
Opened 2023-04-19 14:05 UTC by sushi2all

A document may be generated in a specific way and then rotated in a pdf editor. When this happens the height and width stored in the file do not actually change, which leads to a canvas with the original height and width, but the content, being rotated, appears squeezed within the page.

This commit attempts to avoid this side effect, but requires additional tweaking to center the canvas and thorough testing.

2023-04-25 14:35 UTC, hrynko requested changes
Hi @sushi2all,

Thanks for opening this PR. There is indeed an issue with both rotated documents and the `rotation` prop.

However, the proposed changes to the `getPageDimensions` method do not completely solve the problem. Therefore, I suggest to revert them and apply [this patch](https://github.com/hrynko/vue-pdf-embed/files/11323629/136.patch). After that, please commit and push the changes to this branch.

Again, feel free to contact me if you need help. Thanks in advance!

2023-04-25 14:35 UTC, hrynko commented on src/vue-pdf-embed.vue
> +      return invertDimensions ? [height, width] : [width, height]
Please revert these changes by applying this suggestion

```suggestion

      return [width, height]
```

2023-04-26 10:46 UTC, hrynko requested changes

2023-04-26 10:46 UTC, hrynko commented on src/vue-pdf-embed.vue
> +             })
```suggestion
              scale: 1,
              rotation: 0,
            })
```

2023-04-26 10:46 UTC, hrynko commented on src/vue-pdf-embed.vue
>              const page = await this.document.getPage(pageNum)
`pageRotation` depends on `page`, thus must be defined after 

```suggestion
            const page = await this.document.getPage(pageNum)
            const pageRotation = this.rotation + page.rotate
```

2023-04-26 10:46 UTC, hrynko commented on src/vue-pdf-embed.vue
> +                 : page.view[3] / page.view[2]
```suggestion
                ? page.view[2] / page.view[3]
                : page.view[3] / page.view[2]
```

2023-04-26 10:46 UTC, hrynko commented on src/vue-pdf-embed.vue
> +                div1,
```suggestion
                page,
                div1,
```

2023-04-26 10:46 UTC, hrynko commented on src/vue-pdf-embed.vue
> +            rotation
```suggestion
            rotation,
```

2023-04-26 10:46 UTC, hrynko commented on src/vue-pdf-embed.vue
> +          rotation
```suggestion
          rotation,
```

2023-04-26 10:51 UTC, hrynko approved these changes

2023-04-26 11:32 UTC, sushi2all commented
Hi @hrynko, the pdf now looks good and for me that would be enough, but I noticed the following on the demo app:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/1043732/234562231-a17a14bd-c74e-4cc1-a79b-b8704d3fa053.png">

I always disabled text annotations myself, so I haven't seen any so far. Are they getting rotated too?

2023-04-26 11:38 UTC, hrynko commented
> Are they getting rotated too?

Yes, rotation is applied for both text and annotation layers as well, so they "follow" the page orientation

2023-04-26 11:43 UTC, sushi2all commented
> > Are they getting rotated too?
> 
> Yes, rotation is applied for both text and annotation layers as well, so they "follow" the page orientation

Do you think we can find a way to rotate the annotation coordinates, but maintain the orientation of each single annotation?

2023-04-26 11:59 UTC, hrynko commented
I assume this to be an intended behavior

2023-04-26 12:03 UTC, sushi2all commented
If that's the case then no problem for me. We can close the issue.

Just in case this may be needed in the future. I was playing around with the code and found this can be achieved by adding a `transform: rotate(X)` to the `.annotationLayer .popup` css properties, with X being passed on via a css variable through computed properties.

Happy to contribute if needed.

2023-04-26 17:00 UTC, sushi2all commented
Hi @hrynko, do I need to do anything else for the pull request to be merged?

2023-04-26 17:56 UTC, hrynko commented
No, I will merge it myself and prepare a release. Thanks for your efforts!

2023-04-26 19:56 UTC, sushi2all commented
Thank you for your responsiveness and support! It might have been a simple thing, but I've learned a lot 🙏🏻

2023-04-27 05:39 UTC, merged

2023-04-27 05:45 UTC, hrynko commented
Glad to hear that, it was a pleasure to cooperate with you