Update vue-pdf-embed.vue
hrynko/vue-pdf-embed pull request #26
Opened 2022-04-27 10:04 UTC by Geschwirr

This PR fixes a height/width bug where the pdf gets distorted on rotate due to height/width not being swapped around.

2022-04-28 09:34 UTC, hrynko requested changes
Looks good. However, please consider the following suggestion.

2022-04-28 09:34 UTC, hrynko commented on src/vue-pdf-embed.vue
> +            }
```suggestion
            if ((this.rotation / 90) % 2) {
              canvas.style.width = `${Math.floor(actualHeight)}px`
              canvas.style.height = `${Math.floor(actualWidth)}px`
            } else {
              canvas.style.width = `${Math.floor(actualWidth)}px`
              canvas.style.height = `${Math.floor(actualHeight)}px`
            }
```

2022-05-03 06:42 UTC, Geschwirr commented
Updated and tested

2022-05-03 15:20 UTC, hrynko approved these changes

2022-05-04 07:20 UTC, merged