Add id for each page canvas
hrynko/vue-pdf-embed pull request #7
Opened 2022-01-17 10:00 UTC by hgoncalves

2022-01-17 15:42 UTC, hgoncalves commented
Hi @hrynko, thanks just added the description and a use case

2022-01-17 16:24 UTC, hrynko commented
I find it not quite flexible. Can you consider adding an `id` prop for the component, which, if defined, would naturally be assigned to the wrapper `div` element, and beyond that to all child `svg` elements, but postfixed with page numbers?

So that `<vue-pdf-embed id="my-pdf" ... />` will result in:

```html
<div id="my-pdf">
  <svg id="my-pdf-1" ... />
  <svg id="my-pdf-2" ... />
  <svg id="my-pdf-3" ... />
</div>
```

2022-01-17 16:44 UTC, hgoncalves commented
Hi, you're absolutely right I will do that and let you know as soon as it's done.

2022-01-18 08:05 UTC, hgoncalves commented
Just pushed the changes you suggested

2022-01-18 12:12 UTC, hrynko requested changes
Please also revert `package-lock.json` changes, since this PR does not change dependencies.

2022-01-18 12:12 UTC, hrynko commented on src/vue-pdf-embed.vue
> +    <canvas v-for="pageNum in pageNums" :key="pageNum" />
Let's just override `id` for simplicity

```suggestion
  <div :id="id">
    <canvas
      v-for="pageNum in pageNums"
      :key="pageNum"
      :id="id && `${id}-${pageNum}`"
    />
```

2022-01-18 12:12 UTC, hrynko commented on src/vue-pdf-embed.vue
> +    documentId: {
In addition to the above

```suggestion
    id: {
```

2022-01-18 12:12 UTC, hrynko commented on src/vue-pdf-embed.vue
> +      required: false,
Default value should be set for each props that are not marked as `required` (https://eslint.vuejs.org/rules/require-default-prop.html)

```suggestion
      default: null,
```

2022-01-18 12:12 UTC, hrynko commented on src/vue-pdf-embed.vue
> +     * Id of the document to display
Technically, this is not a document ID

```suggestion
     * Component identifier (inherited by child SVGs with page number
     * postfixes).
```

2022-01-18 12:48 UTC, hgoncalves commented
Done ;)

2022-01-18 16:17 UTC, hrynko approved these changes

2022-01-18 16:26 UTC, hrynko requested changes
I don't think `pageClass` prop is necessary, since classes are flexible enough to be added as follows:

```html
<template>
  <vue-pdf-embed class="my-pdf" ... />
</template>

<style>
.my-pdf svg {
  ...
}
</style>
```

Please revert 9261bda

2022-01-18 16:41 UTC, hrynko approved these changes

2022-01-19 16:20 UTC, merged

2022-01-19 16:20 UTC, hrynko commented
Thank you for your contribution @hgoncalves!

These changes will be included in the next release.

2022-01-19 16:32 UTC, hgoncalves commented
> Thank you for your contribution @hgoncalves!
> 
> These changes will be included in the next release.

Thanks to you, for this package and your disposal.

2022-02-09 10:12 UTC, hrynko commented
UPD: These changes were included in `1.0.8`

2022-02-09 10:13 UTC, hgoncalves commented
Nice thanks