Use less broken advanced example
hrynko/vue-pdf-embed pull request #79
Opened 2022-08-23 19:05 UTC by MarsOrBust24

JSFiddle is being JSfiddle, it's not displaying the original example.

2022-08-24 12:55 UTC, MarsOrBust24 commented
Addresses #78

2022-11-06 16:08 UTC, hrynko requested changes
Hi @FossPrime,

Thanks for opening this PR. Please consider the following suggestion.

2022-11-06 16:08 UTC, hrynko commented on README.md
> +[Advanced Usage Demo (StackBlitz)](https://stackblitz.com/fork/vue-pdf-embed)
```suggestion
[Advanced Usage Demo (JSFiddle)](https://jsfiddle.net/hrynko/we7p5uq4)

[Advanced Usage Demo (StackBlitz)](https://stackblitz.com/fork/vue-pdf-embed)
```

Let's keep the JSFiddle examples for now and add StackBlitz as a complement

2022-11-06 16:20 UTC, FossPrime commented
I've confirmed the example works on Firefox and Chrome.

With a package.json under demo, this could easily run directly from the git repo. stackblitz.com/fork/github/hrynko/vue-pdf-embed/tree/master/demo

See vite.new/vue , vite.new , vite.new/vanilla-ts and vite.new/vue-ts

2022-11-06 17:29 UTC, hrynko commented
I see your point, but the JSFiddle example is not broken. It still works in some environments. Thus, I would keep both examples, so that the one can choose the preferred editor.

2022-11-06 19:02 UTC, FossPrime commented
I can confirm the JSFiddle Advanced example is now working again in Firefox and Chrome. Stackblitz Classic's WebContainers are a good runtime, but it is not a good editor for Vue projects. Stackblitz CloudFlow is good for running and editing, but requires a special git repo and is not usable in incognito.

2022-11-06 21:15 UTC, hrynko commented on README.md
> +[Advanced Usage Demo (StackBlitz)](https://stackblitz.com/fork/vue-pdf-embed)
```suggestion
[Advanced Usage Demo (StackBlitz)](https://stackblitz.com/fork/vue-pdf-embed)
```

2022-11-06 21:17 UTC, merged

2022-11-06 21:17 UTC, hrynko commented
Thanks, I appreciate it 👍